# Generated by Django 4.2.13 on 2024-06-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('voto1', models.PositiveIntegerField()),
                ('voto2', models.PositiveIntegerField()),
                ('voto3', models.PositiveIntegerField()),
                ('voto4', models.PositiveIntegerField()),
                ('voto5', models.PositiveIntegerField()),
            ],
        ),
    ]
