# Generated by Django 4.2.13 on 2024-06-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cienti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='voto1',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='voto2',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='voto3',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='voto4',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='voto5',
        ),
        migrations.AddField(
            model_name='voto',
            name='cor',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('White', 'White')], default='Black', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voto',
            name='dispositivo',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Notebook', 'Notebook'), ('Tablet', 'Tablet'), ('Smartphone', 'Smartphone'), ('Outro', 'Outro')], default='Smartphone', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voto',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro/Prefiro não dizer')], default='M', max_length=1, verbose_name='gênero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voto',
            name='idade',
            field=models.PositiveSmallIntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voto',
            name='opiniao',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Muito Favorável'), (2, 'Favorável'), (3, 'Neutra'), (4, 'Desfavorável'), (5, 'Muito Desfavorável')], default=3),
            preserve_default=False,
        ),
    ]
