# Generated by Django 4.2.13 on 2024-06-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cienti', '0002_remove_voto_nome_remove_voto_voto1_remove_voto_voto2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='opiniao',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Muito Favorável'), (4, 'Favorável'), (3, 'Neutra'), (2, 'Desfavorável'), (1, 'Muito Desfavorável')]),
        ),
    ]
