# Generated by Django 4.2.13 on 2024-06-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cienti', '0003_alter_voto_opiniao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='cor',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('White', 'White')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voto',
            name='dispositivo',
            field=models.CharField(blank=True, choices=[('Desktop', 'Desktop'), ('Notebook', 'Notebook'), ('Tablet', 'Tablet'), ('Smartphone', 'Smartphone'), ('Outro', 'Outro')], max_length=10, null=True),
        ),
    ]
