# Generated by Django 4.2.13 on 2024-06-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cienti', '0004_alter_voto_cor_alter_voto_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Prefiro não dizer')], max_length=1, verbose_name='gênero'),
        ),
    ]
